services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=true
            - WDS_SOCKET_PORT=0
            - NODE_ENV=development
            - PORT=3000
    
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=true
            - WDS_SOCKET_PORT=0
            - NODE_ENV=development
            - PORT=3000
        command: ["npm", "run", "test"]